dataloader_name: DataLoader_MEAD_A13L74
train_dataset_path: 'dataset/train_MEAD_A13L74.json'
test_dataset_path: 'dataset/test_MEAD_A13L74.json'
batch_size: 1
num_workers: 1

model_name: Model_LSTM
n_epoches: 1000
learning_rate: 1.0e-4
optimizer: Adam
loss: MSELoss
input_ndim: 13
output_ndim: 136

save_path: 'results/MEAD_A13L74'
save_epoch: 100

use_pretrain: False
pretrain_path: 'results/MEAD_A13L74/best_model.pt'

export_vid2vid: False
driving_path: 'results/imaginaire/MEAD_A13L74/driving'
reference_path: 'results/imaginaire/MEAD_A13L74/reference'

calculate_lmd: True